[UNC;PSI;NOC;Infraestructura;Storage;EMC-x-vmstores]
    update no
    diskstats_iops.update no
    diskstats_iops.graph_title IOPS Lecturas por vmstores
    diskstats_iops.graph_category IOPS
    diskstats_iops.graph_args --base 1000
    diskstats_iops.graph_vlabel IOs/sec
    diskstats_iops.vm_a.label vmstores_a
    diskstats_iops.vm_b.label vmstores_b
    diskstats_iops.vm_c.label vmstores_c
    diskstats_iops.vm_d.label vmstores_d
    diskstats_iops.vm_e.label vmstores_e
    diskstats_iops.vm_f.label vmstores_f
    diskstats_iops.vm_g.label vmstores_g
    diskstats_iops.vm_h.label vmstores_h
    diskstats_iops.vm_i.label vmstores_i
    diskstats_iops.vm_j.label vmstores_j
    diskstats_iops.vm_k.label vmstores_k
    diskstats_iops.vm_l.label vmstores_l
    diskstats_iops.vm_m.label vmstores_m
    diskstats_iops.graph_order vm_a vm_b vm_c vm_d vm_e vm_f vm_g vm_h vm_i vm_j vm_k vm_l vm_m
    	diskstats_iops.vm_a.sum \
          UNC;PSI;NOC;Servicios;Correo;airedale4.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;airedale4.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Redes;Monitoreo;cacti.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Redes;Monitoreo;cacti.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;convenios.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;convenios.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;FFyH;filosofia.unc.edu.ar:diskstats_iops.hdd.rdio \
          GrULiC;grulic.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          GrULiC;grulic.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Redes;Trafico;ipam.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Redes;Trafico;ipam.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;DTC;ispconfig.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;DTC;ispconfig.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-catalogo.psi.unc.edu.ar:diskstats_iops.xvda1.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-catalogo.psi.unc.edu.ar:diskstats_iops.xvdb1.rdio \
          UNC;PSI;NOC;Redes;Log;log-process.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Redes;Log;log-process.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Zope;ocw-zope.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Zope;ocw-zope.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Zope;ocw-zope.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;Java;rdu-4.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;rdu-4.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Webs;redmine-unc.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Webs;redmine-unc.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;SPGI;spgi-inscripcion.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;SPGI;spgi-inscripcion.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;SPGI;spgi-inscripcion.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;SPGI;spgi-inscripcion.psi.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;PSI;NOC;Servicios;tehuelche.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;usuario-comdoc-demo:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;usuario-comdoc-demo:diskstats_iops.xvdb.rdio 
    	diskstats_iops.vm_b.sum \
          UNC;PSI;NOC;Servicios;Java;comdoc-test.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;comdoc-test.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-u12.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-u12.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-u12.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;kolla3.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;kolla3.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;ldap-gads.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;ldap-gads.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Infraestructura;Datacenter;ocs.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Infraestructura;Datacenter;ocs.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Correo;pandora.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;pandora.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;pdf.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;pdf.unc.edu.ar:diskstats_iops.xvdb.rdio 
    	diskstats_iops.vm_c.sum \
          UNC;PSI;NOC;Redes;Firewall;atomant.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Redes;Firewall;atomant.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Infraestructura;Monitoreo;Bigbrother;bigbrother.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Infraestructura;Monitoreo;Bigbrother;bigbrother.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Infraestructura;Datacenter;cobbler.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Infraestructura;Datacenter;cobbler.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-3.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-3.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-3-12.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-3-12.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-3-12.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-3-18.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-3-18.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-3-18.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-d7.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-d7.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-d7.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;FL;lenguas-uncterm.psi.unc.edu.ar:diskstats_iops.hda.rdio \
          UNC;FL;lenguas-uncterm.psi.unc.edu.ar:diskstats_iops.hdb.rdio \
          UNC;PSI;NOC;Servicios;Java;nodejs-nodo1.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;nodejs-nodo1.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;radioarte.unc.edu.ar:diskstats_iops.xvda1.rdio \
          UNC;PSI;NOC;Servicios;radioarte.unc.edu.ar:diskstats_iops.xvdb1.rdio \
          UNC;PSI;NOC;Servicios;Correo;schnauzer1.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;schnauzer1.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Correo;tortuga.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;tortuga.unc.edu.ar:diskstats_iops.xvdb.rdio 
    	diskstats_iops.vm_d.sum \
          UNC;PSI;NOC;Servicios;Correo;airedale1.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;airedale1.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;dspace-demo.psi.unc.edu.ar:diskstats_iops.hda.rdio \
          UNC;PSI;NOC;Servicios;Java;dspace-demo.psi.unc.edu.ar:diskstats_iops.hdb.rdio \
          UNC;PSI;NOC;Servicios;Java;dspace-demo.psi.unc.edu.ar:diskstats_iops.hdc.rdio \
          UNC;PSI;NOC;Redes;Acceso;jacinto.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Redes;Acceso;jacinto.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;Sistemas;Bibliotecas;koha-community-es:diskstats_iops.xvda.rdio \
          UNC;PSI;Sistemas;Bibliotecas;koha-community-es:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Correo;mail-back-2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;mail-back-2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;pagos.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;pagos.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Zope;periodico-zope.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Zope;periodico-zope.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Zope;periodico-zope.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;Zope;periodico-zope.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;PSI;NOC;Servicios;Correo;schnauzer3.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;schnauzer3.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;sigeva-test2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;sigeva-test2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;sigeva-test2.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;Java;sigeva-test2.psi.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;PSI;NOC;Servicios;Correo;tortuga-2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;tortuga-2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio 
    	diskstats_iops.vm_e.sum \
          UNC;PSI;NOC;Servicios;BDs;databases-pg.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;FFyH;filosofia.unc.edu.ar:diskstats_iops.hda.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-d6.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-d6.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-d6.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;Correo;mail-sec.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;mail-sec.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;nuxeo-2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;nuxeo-2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;olaen.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;olaen.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Correo;phplist.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;phplist.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Guarani;preinscripcion-db.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Guarani;preinscripcion-db.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Guarani;preinscripcion-db.psi.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;PSI;NOC;Servicios;Guarani;preinscripcion-db.psi.unc.edu.ar:diskstats_iops.xvde.rdio \
          UNC;PSI;NOC;Servicios;Java;punku-background.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;punku-background.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;punku-background.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;salud-frontend-prod.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;salud-frontend-prod.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Correo;vtitan.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;vtitan.psi.unc.edu.ar:diskstats_iops.xvdb.rdio 
    	diskstats_iops.vm_f.sum \
          ANC;anc-sauco.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          ANC;anc-sauco.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          ANC;anc-sauco.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;FaMAF;famaf-algoritmosii-2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;FaMAF;famaf-algoritmosii-2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Guarani;guarana.unc.edu.ar:diskstats_iops.hda.rdio \
          UNC;PSI;NOC;Servicios;Guarani;guarana.unc.edu.ar:diskstats_iops.hdb.rdio \
          UNC;PSI;NOC;Servicios;Guarani;guarana.unc.edu.ar:diskstats_iops.hdc.rdio \
          UNC;PSI;NOC;Servicios;Backup;mike.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Backup;mike.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Redes;DNS;ns2-2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Redes;DNS;ns2-2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;openid.unc.edu.ar:diskstats_iops.hda.rdio \
          UNC;PSI;NOC;Servicios;Java;openid.unc.edu.ar:diskstats_iops.hdb.rdio \
          UNC;PSI;NOC;Infraestructura;openvas.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Infraestructura;openvas.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Webs;redmine.unc.edu.ar:diskstats_iops.hda.rdio \
          UNC;PSI;NOC;Servicios;Webs;redmine.unc.edu.ar:diskstats_iops.hdb.rdio \
          UNC;PSI;NOC;Servicios;Zope;zope-dev.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Zope;zope-dev.psi.unc.edu.ar:diskstats_iops.xvdb.rdio 
    	diskstats_iops.vm_g.sum \
          UNC;PSI;NOC;Infraestructura;Datacenter;cobbler.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-ifx2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-ifx2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-ifx2.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-redis.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-redis.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Guarani;guarani-nodo.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Guarani;guarani-nodo.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;id-dev.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;id-dev.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Redes;Acceso;jacinto-2.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Redes;Acceso;jacinto-2.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-dev.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-dev.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;micure.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;micure.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;nodejs-nodo2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;nodejs-nodo2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;pri-kuntur.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;pri-kuntur.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Proxy;www-proxylb03.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Proxy;www-proxylb03.psi.unc.edu.ar:diskstats_iops.xvdb.rdio 
    	diskstats_iops.vm_h.sum \
          UNC;PSI;NOC;Servicios;Guarani;guarani-dev-psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Guarani;guarani-dev-psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Guarani;guarani-test.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Guarani;guarani-test.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;internacionales.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;internacionales.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Correo;mail-back.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;mail-back.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Backup;pg-amanda.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Backup;pg-amanda.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Redes;Telefonia;provisioning.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Redes;Telefonia;provisioning.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Redes;Proxy;proxy2.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Redes;Proxy;proxy2.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;psi-svn.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;psi-svn.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;SPGI;spgi-mapuche.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;SPGI;spgi-mapuche.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;SPGI;spgi-mapuche.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;Backup;vsinapsis-2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Backup;vsinapsis-2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio 
    	diskstats_iops.vm_i.sum \
          UNC;PSI;NOC;Servicios;Correo;airedale3.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;airedale3.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;comdoc-2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;comdoc-2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-8-4.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-8-4.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-8-4.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-8-4.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-8-4.unc.edu.ar:diskstats_iops.xvde.rdio \
          UNC;PSI;NOC;Servicios;dspace-tematiq.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;dspace-tematiq.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;dspace-tematiq.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;FCA;fca-ocs.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;FCA;fca-ocs.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;FFyH;ffyh-www.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;FFyH;ffyh-www.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-u14.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-u14.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-u14.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;Java;nahuel-test.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;nahuel-test.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;nahuel-test.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;Webs;ocw-www.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Webs;ocw-www.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Zope;periodico-www.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Zope;periodico-www.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Zope;periodico-zope-beta.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Zope;periodico-zope-beta.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Zope;periodico-zope-beta.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;SPGI;pilaga.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;SPGI;pilaga.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;SPGI;pilaga.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;SPGI;pilaga.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;Psyche;psyche-pirula.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;Psyche;psyche-pirula.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;Psyche;psyche-pirula.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;PSI;NOC;Servicios;Correo;schnauzer2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;schnauzer2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Webs;seu-www.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Webs;seu-www.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;sigeva2.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;sigeva2.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;yacare-test.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;yacare-test.psi.unc.edu.ar:diskstats_iops.xvdb.rdio 
    	diskstats_iops.vm_j.sum \
          UNC;PSI;NOC;Servicios;Java;archiva.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;archiva.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-ifx1.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-ifx1.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-ifx1.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;debmaker.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;debmaker.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;debmaker.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;FFyH;filosofia.unc.edu.ar:diskstats_iops.hde.rdio \
          UNC;PSI;NOC;Servicios;Bokeh;oca-bokeh.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Bokeh;oca-bokeh.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;unc-box.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;unc-box.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Proxy;www-proxylb01.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Proxy;www-proxylb01.psi.unc.edu.ar:diskstats_iops.xvdb.rdio 
    	diskstats_iops.vm_k.sum \
          UNC;PSI;NOC;Servicios;abc.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;abc.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Correo;airedale2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;airedale2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;comedorws.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;comedorws.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Redes;Eduroam;eduroam2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Redes;Eduroam;eduroam2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;FaMAF;famaf-ccad.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;FaMAF;famaf-ccad.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;FFyH;ffyh-leibniz.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;FFyH;ffyh-leibniz.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;noc-svn.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;noc-svn.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;noc-svn.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Redes;DNS;ns3-2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Redes;DNS;ns3-2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Correo;phplist-unc.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Correo;phplist-unc.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;SAA;saa-artec.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;SAA;saa-artec.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;SPGI;sanaviron.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;SPGI;sanaviron.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;SPGI;sanaviron.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;SPGI;sanaviron.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;PSI;NOC;Servicios;Proxy;www-proxylb02.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Proxy;www-proxylb02.psi.unc.edu.ar:diskstats_iops.xvdb.rdio 
    	diskstats_iops.vm_l.sum \
          UNC;PSI;NOC;Servicios;Java;daspu-micure-test.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;daspu-micure-test.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;SPGI;diaguita-dev.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;SPGI;diaguita-dev.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;SPGI;diaguita-dev.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;SPGI;diaguita-dev.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;PSI;NOC;Servicios;gads-dev.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;gads-dev.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;gads-dev.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;gads-dev.psi.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;SPGI;o3.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;SPGI;o3.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;SPGI;o3.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;SPGI;o3.psi.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;PSI;NOC;Servicios;Java;pasamanos.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;pasamanos.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;punku.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Java;punku.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;punku.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;SPGI;sanaviron-dev.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;SPGI;sanaviron-dev.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;SPGI;sanaviron-dev.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;SPGI;sanaviron-dev.unc.edu.ar:diskstats_iops.xvde.rdio 
    	diskstats_iops.vm_m.sum \
          UNC;PSI;NOC;Infraestructura;Datacenter;cobbler.psi.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-9-1.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-9-1.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-9-1.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-9-1.psi.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-9-2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-9-2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-9-2.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;Docker;docker1.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Docker;docker1.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;ftpsoporte-2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;ftpsoporte-2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;gestor-proyectos-2.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;gestor-proyectos-2.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Guarani;kolla3-5.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;Guarani;kolla3-5.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Guarani;kolla3-5.psi.unc.edu.ar:diskstats_iops.xvdc.rdio \
          UNC;PSI;NOC;Servicios;monse-intranet-1.psi.unc.edu.ar:diskstats_iops.xvda.rdio \
          UNC;PSI;NOC;Servicios;monse-intranet-1.psi.unc.edu.ar:diskstats_iops.xvdb.rdio \
          UNC;PSI;NOC;Servicios;Java;rdu-4.psi.unc.edu.ar:diskstats_iops.xvdd.rdio \
          UNC;PSI;NOC;Infraestructura;Guardian;zm-3.psi.unc.edu.ar:diskstats_iops.xvdc.rdio 
 
    diskstats_iops_1.update no
    diskstats_iops_1.graph_title IOPS Escrituras por vmstores
    diskstats_iops_1.graph_category IOPS
    diskstats_iops_1.graph_args --base 1000
    diskstats_iops_1.graph_vlabel IOs/sec
    diskstats_iops_1.vma.label vmstores_a
    diskstats_iops_1.vmb.label vmstores_b
    diskstats_iops_1.vmc.label vmstores_c
    diskstats_iops_1.vmd.label vmstores_d
    diskstats_iops_1.vme.label vmstores_e
    diskstats_iops_1.vmf.label vmstores_f
    diskstats_iops_1.vmg.label vmstores_g
    diskstats_iops_1.vmh.label vmstores_h
    diskstats_iops_1.vmi.label vmstores_i
    diskstats_iops_1.vmj.label vmstores_j
    diskstats_iops_1.vmk.label vmstores_k
    diskstats_iops_1.vml.label vmstores_l
    diskstats_iops_1.vmm.label vmstores_m
    diskstats_iops_1.graph_order vma vmb vmc vmd vme vmf vmg vmh vmi vmj vmk vml vmm
    	diskstats_iops_1.vma.sum \
          UNC;PSI;NOC;Servicios;Correo;airedale4.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;airedale4.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Redes;Monitoreo;cacti.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Redes;Monitoreo;cacti.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;convenios.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;convenios.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;FFyH;filosofia.unc.edu.ar:diskstats_iops.hdd.wrio \
          GrULiC;grulic.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          GrULiC;grulic.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Redes;Trafico;ipam.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Redes;Trafico;ipam.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;DTC;ispconfig.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;DTC;ispconfig.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-catalogo.psi.unc.edu.ar:diskstats_iops.xvda1.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-catalogo.psi.unc.edu.ar:diskstats_iops.xvdb1.wrio \
          UNC;PSI;NOC;Redes;Log;log-process.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Redes;Log;log-process.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Zope;ocw-zope.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Zope;ocw-zope.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Zope;ocw-zope.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;Java;rdu-4.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;rdu-4.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Webs;redmine-unc.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Webs;redmine-unc.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;SPGI;spgi-inscripcion.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;SPGI;spgi-inscripcion.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;SPGI;spgi-inscripcion.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;SPGI;spgi-inscripcion.psi.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;PSI;NOC;Servicios;tehuelche.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;usuario-comdoc-demo:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;usuario-comdoc-demo:diskstats_iops.xvdb.wrio 
    	diskstats_iops_1.vmb.sum \
          UNC;PSI;NOC;Servicios;Java;comdoc-test.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;comdoc-test.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-u12.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-u12.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-u12.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;kolla3.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;kolla3.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;ldap-gads.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;ldap-gads.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Infraestructura;Datacenter;ocs.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Infraestructura;Datacenter;ocs.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Correo;pandora.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;pandora.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;pdf.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;pdf.unc.edu.ar:diskstats_iops.xvdb.wrio 
    	diskstats_iops_1.vmc.sum \
          UNC;PSI;NOC;Redes;Firewall;atomant.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Redes;Firewall;atomant.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Infraestructura;Monitoreo;Bigbrother;bigbrother.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Infraestructura;Monitoreo;Bigbrother;bigbrother.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Infraestructura;Datacenter;cobbler.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Infraestructura;Datacenter;cobbler.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-3.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-3.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-3-12.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-3-12.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-3-12.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-3-18.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-3-18.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-3-18.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-d7.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-d7.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-d7.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;FL;lenguas-uncterm.psi.unc.edu.ar:diskstats_iops.hda.wrio \
          UNC;FL;lenguas-uncterm.psi.unc.edu.ar:diskstats_iops.hdb.wrio \
          UNC;PSI;NOC;Servicios;Java;nodejs-nodo1.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;nodejs-nodo1.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;radioarte.unc.edu.ar:diskstats_iops.xvda1.wrio \
          UNC;PSI;NOC;Servicios;radioarte.unc.edu.ar:diskstats_iops.xvdb1.wrio \
          UNC;PSI;NOC;Servicios;Correo;schnauzer1.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;schnauzer1.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Correo;tortuga.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;tortuga.unc.edu.ar:diskstats_iops.xvdb.wrio 
    	diskstats_iops_1.vmd.sum \
          UNC;PSI;NOC;Servicios;Correo;airedale1.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;airedale1.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;dspace-demo.psi.unc.edu.ar:diskstats_iops.hda.wrio \
          UNC;PSI;NOC;Servicios;Java;dspace-demo.psi.unc.edu.ar:diskstats_iops.hdb.wrio \
          UNC;PSI;NOC;Servicios;Java;dspace-demo.psi.unc.edu.ar:diskstats_iops.hdc.wrio \
          UNC;PSI;NOC;Redes;Acceso;jacinto.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Redes;Acceso;jacinto.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;Sistemas;Bibliotecas;koha-community-es:diskstats_iops.xvda.wrio \
          UNC;PSI;Sistemas;Bibliotecas;koha-community-es:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Correo;mail-back-2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;mail-back-2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;pagos.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;pagos.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Zope;periodico-zope.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Zope;periodico-zope.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Zope;periodico-zope.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;Zope;periodico-zope.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;PSI;NOC;Servicios;Correo;schnauzer3.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;schnauzer3.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;sigeva-test2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;sigeva-test2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;sigeva-test2.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;Java;sigeva-test2.psi.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;PSI;NOC;Servicios;Correo;tortuga-2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;tortuga-2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio 
    	diskstats_iops_1.vme.sum \
          UNC;PSI;NOC;Servicios;BDs;databases-pg.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;FFyH;filosofia.unc.edu.ar:diskstats_iops.hda.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-d6.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-d6.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-d6.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;Correo;mail-sec.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;mail-sec.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;nuxeo-2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;nuxeo-2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;olaen.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;olaen.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Correo;phplist.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;phplist.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Guarani;preinscripcion-db.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Guarani;preinscripcion-db.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Guarani;preinscripcion-db.psi.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;PSI;NOC;Servicios;Guarani;preinscripcion-db.psi.unc.edu.ar:diskstats_iops.xvde.wrio \
          UNC;PSI;NOC;Servicios;Java;punku-background.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;punku-background.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;punku-background.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;salud-frontend-prod.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;salud-frontend-prod.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Correo;vtitan.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;vtitan.psi.unc.edu.ar:diskstats_iops.xvdb.wrio 
    	diskstats_iops_1.vmf.sum \
          ANC;anc-sauco.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          ANC;anc-sauco.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          ANC;anc-sauco.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;FaMAF;famaf-algoritmosii-2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;FaMAF;famaf-algoritmosii-2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Guarani;guarana.unc.edu.ar:diskstats_iops.hda.wrio \
          UNC;PSI;NOC;Servicios;Guarani;guarana.unc.edu.ar:diskstats_iops.hdb.wrio \
          UNC;PSI;NOC;Servicios;Guarani;guarana.unc.edu.ar:diskstats_iops.hdc.wrio \
          UNC;PSI;NOC;Servicios;Backup;mike.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Backup;mike.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Redes;DNS;ns2-2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Redes;DNS;ns2-2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;openid.unc.edu.ar:diskstats_iops.hda.wrio \
          UNC;PSI;NOC;Servicios;Java;openid.unc.edu.ar:diskstats_iops.hdb.wrio \
          UNC;PSI;NOC;Infraestructura;openvas.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Infraestructura;openvas.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Webs;redmine.unc.edu.ar:diskstats_iops.hda.wrio \
          UNC;PSI;NOC;Servicios;Webs;redmine.unc.edu.ar:diskstats_iops.hdb.wrio \
          UNC;PSI;NOC;Servicios;Zope;zope-dev.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Zope;zope-dev.psi.unc.edu.ar:diskstats_iops.xvdb.wrio 
    	diskstats_iops_1.vmg.sum \
          UNC;PSI;NOC;Infraestructura;Datacenter;cobbler.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-ifx2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-ifx2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-ifx2.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-redis.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-redis.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Guarani;guarani-nodo.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Guarani;guarani-nodo.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;id-dev.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;id-dev.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Redes;Acceso;jacinto-2.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Redes;Acceso;jacinto-2.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-dev.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-dev.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;micure.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;micure.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;nodejs-nodo2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;nodejs-nodo2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;pri-kuntur.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;pri-kuntur.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Proxy;www-proxylb03.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Proxy;www-proxylb03.psi.unc.edu.ar:diskstats_iops.xvdb.wrio 
    	diskstats_iops_1.vmh.sum \
          UNC;PSI;NOC;Servicios;Guarani;guarani-dev-psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Guarani;guarani-dev-psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Guarani;guarani-test.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Guarani;guarani-test.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;internacionales.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;internacionales.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Correo;mail-back.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;mail-back.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Backup;pg-amanda.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Backup;pg-amanda.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Redes;Telefonia;provisioning.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Redes;Telefonia;provisioning.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Redes;Proxy;proxy2.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Redes;Proxy;proxy2.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;psi-svn.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;psi-svn.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;SPGI;spgi-mapuche.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;SPGI;spgi-mapuche.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;SPGI;spgi-mapuche.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;Backup;vsinapsis-2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Backup;vsinapsis-2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio 
    	diskstats_iops_1.vmi.sum \
          UNC;PSI;NOC;Servicios;Correo;airedale3.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;airedale3.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;comdoc-2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;comdoc-2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-8-4.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-8-4.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-8-4.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-8-4.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-8-4.unc.edu.ar:diskstats_iops.xvde.wrio \
          UNC;PSI;NOC;Servicios;dspace-tematiq.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;dspace-tematiq.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;dspace-tematiq.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;FCA;fca-ocs.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;FCA;fca-ocs.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;FFyH;ffyh-www.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;FFyH;ffyh-www.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-u14.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-u14.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Koha;koha-jenkins-u14.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;Java;nahuel-test.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;nahuel-test.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;nahuel-test.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;Webs;ocw-www.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Webs;ocw-www.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Zope;periodico-www.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Zope;periodico-www.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Zope;periodico-zope-beta.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Zope;periodico-zope-beta.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Zope;periodico-zope-beta.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;SPGI;pilaga.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;SPGI;pilaga.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;SPGI;pilaga.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;SPGI;pilaga.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;Psyche;psyche-pirula.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;Psyche;psyche-pirula.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;Psyche;psyche-pirula.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;PSI;NOC;Servicios;Correo;schnauzer2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;schnauzer2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Webs;seu-www.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Webs;seu-www.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;sigeva2.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;sigeva2.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;yacare-test.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;yacare-test.psi.unc.edu.ar:diskstats_iops.xvdb.wrio 
    	diskstats_iops_1.vmj.sum \
          UNC;PSI;NOC;Servicios;Java;archiva.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;archiva.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-ifx1.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-ifx1.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-ifx1.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;debmaker.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;debmaker.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;debmaker.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;FFyH;filosofia.unc.edu.ar:diskstats_iops.hde.wrio \
          UNC;PSI;NOC;Servicios;Bokeh;oca-bokeh.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Bokeh;oca-bokeh.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;unc-box.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;unc-box.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Proxy;www-proxylb01.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Proxy;www-proxylb01.psi.unc.edu.ar:diskstats_iops.xvdb.wrio 
    	diskstats_iops_1.vmk.sum \
          UNC;PSI;NOC;Servicios;abc.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;abc.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Correo;airedale2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;airedale2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;comedorws.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;comedorws.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Redes;Eduroam;eduroam2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Redes;Eduroam;eduroam2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;FaMAF;famaf-ccad.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;FaMAF;famaf-ccad.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;FFyH;ffyh-leibniz.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;FFyH;ffyh-leibniz.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;noc-svn.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;noc-svn.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;noc-svn.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Redes;DNS;ns3-2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Redes;DNS;ns3-2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Correo;phplist-unc.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Correo;phplist-unc.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;SAA;saa-artec.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;SAA;saa-artec.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;SPGI;sanaviron.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;SPGI;sanaviron.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;SPGI;sanaviron.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;SPGI;sanaviron.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;PSI;NOC;Servicios;Proxy;www-proxylb02.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Proxy;www-proxylb02.psi.unc.edu.ar:diskstats_iops.xvdb.wrio 
    	diskstats_iops_1.vml.sum \
          UNC;PSI;NOC;Servicios;Java;daspu-micure-test.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;daspu-micure-test.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;SPGI;diaguita-dev.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;SPGI;diaguita-dev.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;SPGI;diaguita-dev.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;SPGI;diaguita-dev.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;PSI;NOC;Servicios;gads-dev.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;gads-dev.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;gads-dev.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;gads-dev.psi.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;SPGI;o3.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;SPGI;o3.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;SPGI;o3.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;SPGI;o3.psi.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;PSI;NOC;Servicios;Java;pasamanos.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;pasamanos.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;punku.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Java;punku.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;punku.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;SPGI;sanaviron-dev.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;SPGI;sanaviron-dev.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;SPGI;sanaviron-dev.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;SPGI;sanaviron-dev.unc.edu.ar:diskstats_iops.xvde.wrio 
    	diskstats_iops_1.vmm.sum \
          UNC;PSI;NOC;Infraestructura;Datacenter;cobbler.psi.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-9-1.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-9-1.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-9-1.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-9-1.psi.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-9-2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-9-2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;BDs;databases-pg-9-2.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;Docker;docker1.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Docker;docker1.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;ftpsoporte-2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;ftpsoporte-2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;gestor-proyectos-2.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;gestor-proyectos-2.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Guarani;kolla3-5.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;Guarani;kolla3-5.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Guarani;kolla3-5.psi.unc.edu.ar:diskstats_iops.xvdc.wrio \
          UNC;PSI;NOC;Servicios;monse-intranet-1.psi.unc.edu.ar:diskstats_iops.xvda.wrio \
          UNC;PSI;NOC;Servicios;monse-intranet-1.psi.unc.edu.ar:diskstats_iops.xvdb.wrio \
          UNC;PSI;NOC;Servicios;Java;rdu-4.psi.unc.edu.ar:diskstats_iops.xvdd.wrio \
          UNC;PSI;NOC;Infraestructura;Guardian;zm-3.psi.unc.edu.ar:diskstats_iops.xvdc.wrio 
